#!/bin/bash

VERSION="1.6.2"
CONFIG_FILE="${CONFIG_FILE:-$HOME/.config/minecraft-console.config}"

# Make sure the script is not running as root
if [ "$UID" == "0" ]; then
    echo -n "WARNING ! For security reasons: DO NOT RUN THE SERVER AS ROOT "
    c=1
    while [ "$c" -le 5 ]; do
        echo -n "!"
        sleep 1
        ((c = c + 1))
    done
    echo ""
    exit 21
fi

# Functions
defaults() {
    # Default server path is in the root
    server_path="${server_root}/${profile}"
    # Default java
    java="java"
    # Default time
    default_time=5
}

send_server() {
    # Sends the contents to the screen and executes it
    screen -p 0 -S "${profile}" -X stuff "$*$(printf \\r)"
}

is_running() {
    # Checks for the screen running the server
    # shellcheck disable=2046
    return $(pgrep -u "$(whoami)" -f "SCREEN -dmS ${profile}" > /dev/null)
}

check_config() {
    # Scrict is if we need the files to exist already or not.
    if [ -z "${default_time}" ]; then
        echo "'default_time' is not set: '${default_time}'"
    elif [ -n "${player_list_path}" ] && [ ! -d "${player_list_path}" ]; then
        echo "'player_list_path' does not exist: '${player_list_path}'"
    elif [ "${type}" != "minecraft" ]; then
        echo "Profile ${profile} has unsupported 'type' of '${type}'"
    elif [ "${autostart}" != "true" ] && [ "${autostart}" != "false" ]; then
        echo "Profile ${profile} has unsupported 'autostart' of '${autostart}'"
    elif [ -z "${server_path}" ]; then
        echo "Profile ${profile} has blank 'server_path': '${server_path}'"
    elif [ ! -d "${server_path}" ]; then
        echo "Profile ${profile} has 'server_path' that does not exist: '${server_path}'"
    elif [ ! -r "${server_path}" ]; then
        echo "Profile ${profile} has 'server_path' that is not readable: '${server_path}'"
    elif [ ! -w "${server_path}" ]; then
        echo "Profile ${profile} has 'server_path' that is not writeable: '${server_path}'"
    elif [ -z "${server_command}" ]; then
        echo "Profile ${profile} has blank 'server_command': '${server_command}'"
    elif [ "${updateable}" != "vanilla" ] && [ "${updateable}" != "snapshot" ] && \
        [ "${updateable}" != "false" ]; then
        echo "Profile ${profile} has unsupported 'updateable' of '${updateable}'"

    elif [ "$1" == "strict" ]; then
        if [ -n "${world}" ] && [ ! -d "${server_path}/${world}" ]; then
            echo "Profile ${profile} has 'world' that does not exist: '${world}'"
            echo "Is it possible that the server is empty and needs to be updated?"
        elif [ -z "${jar_name}" ]; then
            if [ -n "${jar_search}" ]; then
                echo "Profile ${profile} has no jar file matching its jar_name: '${jar_search}'"
            else
                echo "Profile ${profile} has blank 'jar_name': '${jar_name}'"
            fi
        elif [[ "${jar_name}" =~ [[:space:]] ]]; then
            echo "Profile ${profile} has multiple files matching its jar_name: '${jar_search}'"
            echo "This could also be because of a space in the filename (y u do dis)"
        elif [ ! -f "${server_path}/${jar_name}" ]; then
            echo "Profile ${profile} has 'jar_name' that does not exist: '${jar_name}'"
        elif [ ! -r "${server_path}/${jar_name}" ]; then
            echo "Profile ${profile} has 'jar_name' that is not readable: '${jar_name}'"
        elif [ ! -w "${server_path}/${jar_name}" ]; then
            echo "Profile ${profile} has 'jar_name' that is not writeable: '${jar_name}'"
        else
            return 0
        fi
    else
        # All good
        return 0
    fi
    exit 3
}

start() {
    if is_running; then
        echo "The ${profile} server is already running, use restart, try-restart, or stop"
        return 7
    fi

    # Check if this profile is allowed to be autorun
    if [ "$1" == "auto" ] && [ "${autostart}" == "false" ]; then
        echo "The ${profile} server is not set to be autorun. Server not started"
        return 0
    fi

    cd "${server_path}" ||
        { echo "Cannot enter server location!"; return 12; }
    if [ "${type}" == "minecraft" ]; then
        # Copy the server.properties file to allow for multiple world configurations
        if [ -n "${world}" ] && [ -e "${world}"/server.properties ]; then
            cp -f "${world}"/server.properties server.properties
        fi
    fi

    if [ -d "${player_list_path}" ]; then
        if [ "${type}" == "minecraft" ]; then
            ln -f "${player_list_path}"/minecraft.whitelist "${server_path}"/whitelist.json
            ln -f "${player_list_path}"/minecraft.oplist "${server_path}"/ops.json
            ln -f "${player_list_path}"/minecraft.banlist "${server_path}"/banned-players.json
        fi
    fi

    if [ "${eula}" == "true" ]; then
        echo "eula=true" > "eula.txt"
    fi

    echo "Starting the ${profile} server..."
    if [ ! -x "${jar_name}" ]; then
        echo "${jar_name} is not executable, trying to set it"
        chmod +x "${jar_name}"
        if [ ! -x "${jar_name}" ]; then
            echo "${jar_name} is not executable, cannot start the server"
            return 13
        fi
    fi

    # Launch it
    if [ "$1" == "debug" ]; then
        # Launch without screen for easier debugging
        ${server_command}
    else
        # TODO: make server_command a function
        # shellcheck disable=2086
        screen -dmS "${profile}" ${server_command} &
        echo "${profile} server launched..."
        # Make sure it is running
        sleep 2
        if is_running; then
            echo "${profile} server started."
            # Start the listener if needed
            if [ "${listener}" == "true" ]; then
                listenerstart
            fi
        else
            echo "${profile} server seemes to have crashed!"
            return 9
        fi
    fi
}

stop() {
    if ! is_running; then
        echo "The ${profile} server is not running."
        return 8
    fi

    echo "Sending stop warnings on the ${profile} server"

    # Test if time parameter was specified
    if [ -n "$1" ]; then
        if [ "$1" -gt 0 ]; then
            default_time="$1"
        fi
    fi

    if [ "${type}" == "minecraft" ]; then
        send_server "say SERVER STOPPING/RESTARTING IN ${default_time} SECONDS"
        sync
        sleep "${default_time}"
        send_server "stop"
    fi

    echo -n "Stopping the ${profile} server"
    i=1
    while [ "$i" -le 20 ]; do
        if is_running; then
            echo -n "."
            sleep 1
        else
            break
        fi
        i=$((++i))
    done
    echo "."
    if is_running; then
        echo "Server is not shutting down cleanly."
        return 10
    fi

    # Stop the listener if needed
    if [ "${listener}" == "true" ]; then
        listenerstop
    fi

    echo "Done."
}

status() {
    if is_running; then
        echo "${profile} server is running"
    else
        echo "${profile} server is shut down"
    fi
}

backup() {
    hash rsync 2>/dev/null || { echo "I need rsync but it's not installed"; return 22; }

    if [ -z "${backup_path}" ]; then
        echo "Backups are disabled for the ${profile} profile."
        echo "Update the profile if you want to make backups."
        return 15
    elif ! is_running && echo "$1" | grep -Eivq "(force|f|-f|override)"; then
        echo "The ${profile} server is not running, so no backups need to be made."
        return 0
    else
        echo "Backing up the ${profile} server..."
    fi

    if [ ! -d "${backup_path}" ]; then
        echo "The backup path ${backup_path} for the profile ${profile} does not exist!"
        echo "Creating it now..."
        mkdir "${backup_path}" || return 11
    fi

    if is_running; then
        echo "Suspending saves on the ${profile} server..."
        if [ "${type}" == "minecraft" ]; then
            send_server "say SERVER BACKUP STARTING"
            send_server "save-off"
            send_server "save-all"
        fi
        sleep 2
        sync
        sleep 1
    fi

    echo "Making the backup..."
    date=$(date "+%Y-%m-%dT%H:%M:%S")

    if [ -L "${backup_path}/current" ] && [ -e "${backup_path}/current" ]; then
        echo "Symlink found; making a diff backup"
        rsync -a --link-dest="${backup_path}/current" "${server_path}/" "${backup_path}/back-${date}"
        rm "${backup_path}/current"
    else
        echo "No symlink found; making a clean backup"
        rsync -a "${server_path}/" "${backup_path}/back-${date}"
    fi

    ln -s "${backup_path}/back-${date}" "${backup_path}/current"

    echo "Backup finished"

    if is_running; then
        echo "Re-enabling saves"
        if [ "${type}" == "minecraft" ]; then
            send_server "save-on"
            send_server "say SERVER BACKUP ENDED"
        fi
    fi

    echo "Done."
}

restore() {
    in_time="$1"

    if [ -z "${backup_path}" ]; then
        echo "Backups are disabled for the ${profile} profile."
        echo "Update the profile if you want to use backups."
        return 15
    elif [ ! -d "${backup_path}" ]; then
        echo "Profile ${profile} has a 'backup_path' that does not exist: '${backup_path}'"
        return 3
    fi

    if [ -z "${in_time}" ] || ! date  -d "${in_time}" +%s >/dev/null 2>&1; then
        echo "Incorrect date format. Format: 'YYYY-MM-DD HH:MM:SS'"
        return 2
    fi

    in_utime=$(date -d "${in_time}" +%s)
    out_utime=0

    # Have valid date, find closest date backwards
    cd "${backup_path}" ||
        { echo "Cannot enter backup location!"; return 12; }
    dirs="back*"

    for d in $dirs; do
        backup_time=$(echo "${d}" | sed 's/^back-//; s/T/ /')
        backup_utime=$(date -d "${backup_time}" +%s)

        if [ "${backup_utime}" -le "${in_utime}" ]; then
            if [ "${backup_utime}" -ge "${out_utime}" ]; then
                out_utime="${backup_utime}"
                out_dir="${d}"
            fi
        fi
    done

    if [ -z "${out_dir}" ]; then
        echo "No backup found older than input date"
        return 17
    fi

    echo "Date to restore: $(date -d @"${out_utime}")"
    echo "Directory to remove: ${server_path}"
    echo "Are you sure you want to want to overwrite the server? [y|N]:"

    read -r value
    while :; do
        case "${value}" in
            y|yes|Y)
                # Restore from valid date
                # This does a complete overwrite without removing first
                rsync -a --delete "${backup_path}/${out_dir}/" "${server_path}" || return 16
                return 0
            ;;
            n|no|N)
                echo "Exiting on user command"
                return 0
            ;;
            *)
                echo -n "Please enter [y|N]: "
                read -r value
        esac
    done
}

say() {
    if ! is_running; then
        echo "The ${profile} server is not running."
        return 8
    fi
    if [ "${type}" == "minecraft" ]; then
        send_server "say $*"
    fi
}

command() {
    if ! is_running; then
        echo "The ${profile} server is not running."
        return 8
    fi
    send_server "$*"
}

update() {
    if [ "${updateable}" == "false" ]; then
        echo "The ${profile} server is not set as updateable"
        return 19
    fi

    if [ "${type}" == "minecraft" ]; then
        version_file="https://launchermeta.mojang.com/mc/game/version_manifest.json"
        # Allow for specifiying a specific version
        if [ -n "$1" ]; then
            current_version="$1"
        elif [ "${updateable}" == "vanilla" ]; then
            # Awkward pieces of code that strip the current Minecraft versions from the version file
            current_version=$(\
                wget -q -O - "${version_file}" |
                sed 's/.*"release":"\([0-9a-zA-Z.-]*\)".*/\1/')
            echo "The newest stable version is ${current_version}"
        elif [ "${updateable}" == "snapshot" ]; then
            current_version=$(\
                wget -q -O - "${version_file}" |
                sed 's/.*"snapshot":"\([0-9a-zA-Z.-]*\)".*/\1/')
            echo "The newest snapshot is ${current_version}"
        else
            echo "Unsupported type of Minecraft release. Please fix this profile"
            return 3
        fi

        # Parse the version out of the jar file
        # shellcheck disable=2001
        installed_version=$(\
            echo "${jar_name}" |
            sed 's/minecraft[_-]server\.\([0-9a-zA-Z.-]*\)\.jar/\1/')
        if [ -n "${installed_version}" ]; then
            echo "Your version is ${installed_version}"
        fi

        # Check if the current version is outdated
        if [ "${current_version}" == "${installed_version}" ]; then
            echo "The ${profile} server is up to date"
        else
            if is_running; then
                echo "The ${profile} server is currently running"
                echo -n "Would you like to restart, backup, and update the ${profile} server? [y|N]: "
            else
                echo -n "Would you like to backup and update the ${profile} server? [y|N]: "
            fi

            read -r value
            while :; do
                case "${value}" in
                    y|yes|Y)
                        if is_running; then
                            stop || { echo "Server won't shutdown. Aborting."; return 10; }
                            was_running="true"
                        fi
                        cd "${server_path}" ||
                            { echo "Cannot enter server location!"; return 12; }

                        echo "Backing up..."
                        backup force || { echo "Backup failed! Quitting..."; return 14; }

                        echo "Updating..."
                        download="https://s3.amazonaws.com/Minecraft.Download/versions"
                        wget "${download}/${current_version}/minecraft_server.${current_version}.jar" ||
                            {   echo "Download failed, aborting"
                                if [ "${was_running}" == "true" ]; then
                                    start || { echo "Server won't start back up!"; return 9; }
                                fi
                                return 18; }
                        chmod +x "minecraft_server.${current_version}.jar"
                        if [ -f "${jar_name}" ]; then
                            rm "${jar_name}"
                        fi
                        if [ ! -d "${server_path}/${world}" ]; then
                            mkdir "${server_path}/${world}"
                        fi
                        echo "The ${profile} server was updated to version ${current_version}"

                        if [ "${was_running}" == "true" ]; then
                            # We updated, so we need our new jar_file
                            load_profile strict
                            start || return 9
                        fi
                        return 0
                    ;;
                    n|no|N)
                        echo "Exiting on user command"
                        return 0
                    ;;
                    *)
                        echo -n "Please enter [y|N]: "
                        read -r value
                esac
            done
        fi
    fi
}

list() {
    echo "Profile list:"
    for profile in "${profile_list[@]}"; do
        echo -n "${profile} "
    done
    echo ""
}

see() {
    if ! is_running; then
        echo "The ${profile} server is not running."
        return 8
    fi

    cat > /tmp/screenconfig <<EOF
startup_message off
screen -t 'console' sh -c "tail -n 1000 --follow=name ${server_path}/logs/latest.log"
screen -t 'shell' bash -c "$0 shell ${profile}"
split
focus down
select 'shell'
resize 3
focus up
select 'console'
focus down
EOF
    screen -S "console-${profile}" -c /tmp/screenconfig
    rm /tmp/screenconfig
    screen -S "console-${profile}" -X quit >& /dev/null
}

shell() {
    mode="command"
    while :; do
        if [ "${mode}" == "command" ]; then
            echo -n "c "
        else
            echo -n "s "
        fi
        echo -n "> "
        read -r value
        # shellcheck disable=2086
        set -- ${value}
        case "$1" in
            exit|:q|quit)
                screen -S "console-${profile}" -X quit >& /dev/null
                return 0
            ;;
            nick)
                shift 1
                nick="$*"
            ;;
            help)
                echo "c|s|exit|nick|help"
            ;;
            c|command)
                shift 1
                # Only send something if line is not blank
                if [ -n "$*" ]; then
                    send_server "$*"
                fi
                mode="command"
            ;;
            s|say|chat)
                shift 1
                mode="say"
            ;&
            *)
                # Only send something if line is not blank
                if [ -n "$*" ]; then
                    if [ "${mode}" == "command" ]; then
                        send_server "$*"
                    else
                        if [ -n "${nick}" ]; then
                            send_server "say <${nick}> $*"
                        else
                            send_server "say $*"
                        fi
                    fi
                fi
        esac
    done
}

listener() {
    script="$0"
    if [ -h "$script" ]; then
        script="$(readlink -f "$script")"
    fi
    # shellcheck source=minecraft-listener
    . "$(dirname "$script")/minecraft-listener"
}

listenerstart() {
    screen -dmS "listener-${profile}" "$0" "listener" "${profile}" &
}

listenerstop() {
    screen -S "listener-${profile}" -X quit >& /dev/null
}

new() {
    # Add new profile to config
    if [ ! "$1" ] || [ "$1" == "minecraft" ] || [ "$1" == "vanilla" ]; then
        cat >> "${CONFIG_FILE}" <<'EOF'
vanilla() {
    type="minecraft"
    autostart="true"
    backup_path="/${server_root}/backup/${profile}"
    world="world"
    jar_name="minecraft_server.*.jar"
    server_command="${java} -Xmx4G -Xms2G -jar ${jar_name} nogui"
    updateable="vanilla"
}

EOF
        echo "New vanilla minecraft profile added."
    elif [ "$1" == "modded" ]; then
        cat >> "${CONFIG_FILE}" <<'EOF'
modded() {
    type="minecraft"
    autostart="false"
    backup_path="/${server_root}/backup/${profile}"
    world="world"
    jar_name="forge-*-universal.jar"
    server_command="${java} -Xmx4G -Xms2G -jar ${jar_name} nogui"
    updateable="false"
}

EOF
        echo "New modded minecraft profile added."
    else
        echo "Unknown profile type ${1}."
        return 2
    fi
    echo "Add the new profile to the profile list to activate it."
}

config() {
    # Make sure GNU screen is installed
    hash screen 2>/dev/null || { echo >&2 "I need screen but it's not installed"; return 22; }

    if [ ! -d "${HOME}/.config" ]; then
        mkdir "${HOME}/.config"
    fi
    if ! [ -e "${CONFIG_FILE}" ]; then
        touch "${CONFIG_FILE}"
        cat > "${CONFIG_FILE}" <<'EOF'
# Time for stopping and restarting. Set this if you want a different wait.
#default_time=5

# Root of all Minecraft servers. This does not have to be specified if you want
# to specify each server_path by itself. If you do specify this, you can leave
# each server_path blank, and it will default to server_root/profile_name.
server_root="/var/minecraft"

# Location of the universal whitelist/oplist. Leave blank if you want to use
# seperate ones for each server.
#player_list_path="${server_root}"

# This is agreeing to the Mojang EULA, not mine. See their EULA here:
# https://account.mojang.com/documents/minecraft_eula
# Changing this to true will make all servers EULA be true.
#eula="true"

# The java binary to use. Set this if the default java ("which java") isn't
# what you want to run the servers.
#java="java"

# Profiles
# To make your own, run "console new <type>"
# Exceptable profiles types are "minecraft", for now.
# To disable backups, leave the 'backup_path' blank, eg: backup_path=""
# 'updateable' can equal types "vanilla" or "snapshot" for minecraft.
# "false" will disable updating.
# 'jar_name' can include * wildcards for searching for a jar file, allowing for
# updates without changing this config file. If there is more than one
# minecraft jar file in the folder the search will fail

# The list of servers that the "all" commands will use
profile_list=()

EOF
        echo "Base config created. Run \"$0 new <type>\" to add your first profile."
        return 0
    fi

    if [ -z "$EDITOR" ]; then
        vi "${CONFIG_FILE}" || return 20
    else
        "${EDITOR}" "${CONFIG_FILE}" || return 20
    fi

    # Load the configuration to check it
    echo "Checking new config..."
    # shellcheck source=minecraft-console.config
    . "${CONFIG_FILE}"

    for profile in "${profile_list[@]}"; do
        defaults
        ${profile} >& /dev/null ||
            { echo "Profile ${profile} was not found, but it was in the profile list."; return 4; }
        check_config
    done
    echo "Config looks good."
}

help_text() {
    # Help text
    echo "Java server script version $VERSION by Rycieos"
    echo "Usage: $0 [start|stop|restart|try-restart|backup|restore|say|command|status|update|"
    echo "    see|listener-start|listener-stop|listener-restart|list|config|new] <profile-name>|all"
    echo "Profile settings are at ~/.config/minecraft-console.config. Use $0 config to edit"
    return 1
}

load_profile() {
    if [ -z "${profile}" ]; then
        echo "No Profile specified"
        help_text
    fi
    # Load the profile's settings by calling it as a function
    defaults
    ${profile} >& /dev/null ||
        { echo "Profile ${profile} was not found. Run \"$0 new <type>\" to add it"; exit 4; }

    # Search for the jar file to run if a wildcard was specified in the profile
    if [[ "${jar_name}" == *\** ]]; then
        jar_search="${jar_name}"
        jar_name=$(find "${server_path}/" -maxdepth 1 -name "${jar_name}" \
            -type f -printf "%f\n" 2>/dev/null)
    fi

    check_config "$1"
}

# SCRIPT START

SWITCH="$1"

if [ "${SWITCH}" == "lib" ]; then
    return 0
fi

if [ ! -e "${CONFIG_FILE}" ] && [ "$1" != "config" ]; then
    echo "No config file was found!"
    echo "Please run \"$0 config\""
    exit 5
elif [ "${SWITCH}" != "config" ] && [ "${SWITCH}" != "new" ] && [ "${SWITCH}" != "add" ]; then
    # Load the configuration only if we aren't trying to change it
    # shellcheck source=minecraft-console.config
    . "${CONFIG_FILE}"
fi

if [ "$2" == "all" ]; then
    case "${SWITCH}" in
        start|s)
            for profile in "${profile_list[@]}"; do
                load_profile strict
                start auto
            done
            exit 0
        ;;
        stop|restart|backup|say|command)
            # Shift to get rid of the <command> all. The remainder gets run
            shift 2
            for profile in "${profile_list[@]}"; do
                load_profile strict
                "${SWITCH}" "$@"
            done
            exit 0
        ;;
        status|update)
            # Shift to get rid of the <command> all. The remainder gets run
            shift 2
            for profile in "${profile_list[@]}"; do
                load_profile
                "${SWITCH}" "$@"
            done
            exit 0
        ;;
        see|console|restore)
            echo "$1 is not supported for all profiles at the same time."
            exit 6
        ;;
        config|new|add)
            echo "all is implied for ${1}."
            exit 6
        ;;
    esac
fi

profile="$2"

case "${SWITCH}" in
    start)
        load_profile strict
        start "$3"
    ;;
    stop)
        load_profile strict
        stop "$3"
    ;;
    restart)
        load_profile strict
        stop "$3"
        start "$3"
    ;;
    try-restart)
        load_profile strict
        if is_running; then
            stop "$3" && start "$3"
        fi
    ;;
    status)
        load_profile
        status
    ;;
    backup)
        load_profile strict
        backup "$3"
    ;;
    restore)
        load_profile
        restore "$3"
    ;;
    say)
        load_profile strict
        shift 2
        say "$*"
    ;;
    command)
        load_profile strict
        shift 2
        command "$*"
    ;;
    update)
        load_profile
        update "$3"
    ;;
    see|console)
        load_profile strict
        see
    ;;
    shell)
        load_profile
        shell
    ;;
    listener)
        load_profile
        listener
    ;;
    listener-start)
        load_profile
        listenerstart
    ;;
    listener-stop)
        load_profile
        listenerstop
    ;;
    listener-restart)
        load_profile
        listenerstop
        listenerstart
    ;;
    # Profile agnostic
    list)
        list
    ;;
    new)
        new "$2"
    ;;
    config)
        config
    ;;
    *)
        help_text
esac
exit $?
